apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: pod_example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pod_example
  template:
    metadata:
      labels:
        app: pod_example
    spec:
      containers:
      - name: webserver
        image: nginx:latest
        ports:
        - containerPort: 80
