apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: webserver
  replicas: 2
  selector:
    matchLabels:
      app: pod_example
  template:
    metadata:
      labels:
        app: pod_example
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 0.1Gi
